// <auto-generated />
using ContosoPizza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContosoPizza.Migrations
{
    [DbContext(typeof(ContosoPizzaDbContext))]
    partial class ContosoPizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContosoPizza.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsGlutenFree = false,
                            Name = "Margherita"
                        },
                        new
                        {
                            Id = 2,
                            IsGlutenFree = false,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 3,
                            IsGlutenFree = false,
                            Name = "Gluten-Free Veggie"
                        },
                        new
                        {
                            Id = 4,
                            IsGlutenFree = false,
                            Name = "Hawaiian"
                        },
                        new
                        {
                            Id = 5,
                            IsGlutenFree = false,
                            Name = "Diavola"
                        },
                        new
                        {
                            Id = 6,
                            IsGlutenFree = false,
                            Name = "Quattro Formaggi"
                        },
                        new
                        {
                            Id = 7,
                            IsGlutenFree = false,
                            Name = "Caprese"
                        },
                        new
                        {
                            Id = 8,
                            IsGlutenFree = false,
                            Name = "Napoli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
